#!/usr/bin/env python3

#Function get params (in this case is port, passed via WATO agent rule cunfiguration, hostname and ip addres of host, 
#for which agent will be invoked 
def agent_myspecal_arguments(params, hostname, ipaddress):
    args = []

    args += ["-a", ipaddress]
    args += ["-p", params['port']]


    return args

#register invoke function for our agent
#key value for this dictionary is name part from register datasource of our agent (name="special_agents:myspecial" remember?)
special_agent_info['myspecial'] = agent_myspecal_arguments
